### ISSUE TITLE
Problema al correr test de Selenium

### ISSUE THREAD

**Issue by macadden** [frlp-utn-is-2018/orderingg#36]
Al querer correr el test de Selenium que está en el repo, este falla. Estoy corriendo:
```
$ pytest test_e2e.py
```
Y me devuelve un error que creo que puede ser por el webdriver del Chrome, que no sé cómo instalarlo. Intenté agregando código al test para que vaya a buscar el driver manualmente, pero no lo pude hacer andar. 
¿Cómo hago para instalar el webdriver?

**Comment by RodrigoJacznik** [comment]
Buenas. Te paso el link a la documentación

[http://selenium-python.readthedocs.io/installation.html#drivers](http://selenium-python.readthedocs.io/installation.html#drivers)
Si tenes problemas avísame y lo revisamos.
Saludos.

**Comment by ignacio96** [comment]
Me pasa lo mismo, descargue el web driver de chrome pero no se bien como instalarlo

**Comment by RodrigoJacznik** [comment]
Si estas en Windows tenes extraer el zip y agregar el .exe que está adentro al path del sistema

**Comment by ignacio96** [comment]
Ya lo hice pero me sigue tirando error

**Comment by RodrigoJacznik** [comment]
Que error?

**Comment by ignacio96** [comment]
Un mensaje re largo con mensajes en rojo y al final dice "1 failed, 2 passed in 2.79 seconds"

**Comment by RodrigoJacznik** [comment]
No te voy a poder ayudar si no me pasas el error.

**Comment by ignacio96** [comment]
C:\Users\lanzi\orderingg>pytest test/test_e2e.py
============================= test session starts =============================
platform win32 -- Python 3.6.5, pytest-3.5.1, py-1.5.3, pluggy-0.6.0
rootdir: C:\Users\lanzi\orderingg, inifile:
collected 1 item

test\test_e2e.py F                                                       [100%]

================================== FAILURES ===================================
_____________________________ Ordering.test_title _____________________________

self = <test.test_e2e.Ordering testMethod=test_title>
result = <TestCaseFunction 'test_title'>

    def __call__(self, result=None):
        """
            Does the required setup, doing it here means you don't have to
            call super.setUp in subclasses.
            """

        # Get the app
        self.app = self.create_app()

        self._configured_port = self.app.config.get('LIVESERVER_PORT', 5000)
        self._port_value = multiprocessing.Value('i', self._configured_port)

        # We need to create a context in order for extensions to catch up
        self._ctx = self.app.test_request_context()
        self._ctx.push()

        try:
>           self._spawn_live_server()

..\appdata\local\programs\python\python36\lib\site-packages\flask_testing\utils.py:446:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <test.test_e2e.Ordering testMethod=test_title>

    def _spawn_live_server(self):
        self._process = None
        port_value = self._port_value

        def worker(app, port):
            # Based on solution: http://stackoverflow.com/a/27598916
            # Monkey-patch the server_bind so we can determine the port bound by Flask.
            # This handles the case where the port specified is `0`, which means that
            # the OS chooses the port. This is the only known way (currently) of getting
            # the port out of Flask once we call `run`.
            original_socket_bind = socketserver.TCPServer.server_bind
            def socket_bind_wrapper(self):
                ret = original_socket_bind(self)

                # Get the port and save it into the port_value, so the parent process
                # can read it.
                (_, port) = self.socket.getsockname()
                port_value.value = port
                socketserver.TCPServer.server_bind = original_socket_bind
                return ret

            socketserver.TCPServer.server_bind = socket_bind_wrapper
            app.run(port=port, use_reloader=False)

        self._process = multiprocessing.Process(
            target=worker, args=(self.app, self._configured_port)
        )

>       self._process.start()

..\appdata\local\programs\python\python36\lib\site-packages\flask_testing\utils.py:486:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <Process(Process-1, initial)>

    def start(self):
        '''
            Start child process
            '''
        assert self._popen is None, 'cannot start a process twice'
        assert self._parent_pid == os.getpid(), \
               'can only start a process object created by current process'
        assert not _current_process._config.get('daemon'), \
               'daemonic processes are not allowed to have children'
        _cleanup()
>       self._popen = self._Popen(self)

..\appdata\local\programs\python\python36\lib\multiprocessing\process.py:105:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

process_obj = <Process(Process-1, initial)>

    @staticmethod
    def _Popen(process_obj):
>       return _default_context.get_context().Process._Popen(process_obj)

..\appdata\local\programs\python\python36\lib\multiprocessing\context.py:223:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

process_obj = <Process(Process-1, initial)>

    @staticmethod
    def _Popen(process_obj):
        from .popen_spawn_win32 import Popen
>       return Popen(process_obj)

..\appdata\local\programs\python\python36\lib\multiprocessing\context.py:322:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <multiprocessing.popen_spawn_win32.Popen object at 0x0000023343DD10B8>
process_obj = <Process(Process-1, initial)>

    def __init__(self, process_obj):
        prep_data = spawn.get_preparation_data(process_obj._name)

        # read end of pipe will be "stolen" by the child process
        # -- see spawn_main() in spawn.py.
        rhandle, whandle = _winapi.CreatePipe(None, 0)
        wfd = msvcrt.open_osfhandle(whandle, 0)
        cmd = spawn.get_command_line(parent_pid=os.getpid(),
                                     pipe_handle=rhandle)
        cmd = ' '.join('"%s"' % x for x in cmd)

        with open(wfd, 'wb', closefd=True) as to_child:
            # start process
            try:
                hp, ht, pid, tid = _winapi.CreateProcess(
                    spawn.get_executable(), cmd,
                    None, None, False, 0, None, None, None)
                _winapi.CloseHandle(ht)
            except:
                _winapi.CloseHandle(rhandle)
                raise

            # set attributes of self
            self.pid = pid
            self.returncode = None
            self._handle = hp
            self.sentinel = int(hp)
            util.Finalize(self, _winapi.CloseHandle, (self.sentinel,))

            # send information to child
            set_spawning_popen(self)
            try:
                reduction.dump(prep_data, to_child)
>               reduction.dump(process_obj, to_child)

..\appdata\local\programs\python\python36\lib\multiprocessing\popen_spawn_win32.py:65:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

obj = <Process(Process-1, initial)>, file = <_io.BufferedWriter name=11>
protocol = None

    def dump(obj, file, protocol=None):
        '''Replacement for pickle.dump() using ForkingPickler.'''
>       ForkingPickler(file, protocol).dump(obj)
E       AttributeError: Can't pickle local object 'LiveServerTestCase._spawn_live_server.<locals>.worker'

..\appdata\local\programs\python\python36\lib\multiprocessing\reduction.py:60: AttributeError

During handling of the above exception, another exception occurred:

self = <test.test_e2e.Ordering testMethod=test_title>
result = <TestCaseFunction 'test_title'>

    def __call__(self, result=None):
        """
            Does the required setup, doing it here means you don't have to
            call super.setUp in subclasses.
            """

        # Get the app
        self.app = self.create_app()

        self._configured_port = self.app.config.get('LIVESERVER_PORT', 5000)
        self._port_value = multiprocessing.Value('i', self._configured_port)

        # We need to create a context in order for extensions to catch up
        self._ctx = self.app.test_request_context()
        self._ctx.push()

        try:
            self._spawn_live_server()
            super(LiveServerTestCase, self).__call__(result)
        finally:
            self._post_teardown()
>           self._terminate_live_server()

..\appdata\local\programs\python\python36\lib\site-packages\flask_testing\utils.py:450:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
..\appdata\local\programs\python\python36\lib\site-packages\flask_testing\utils.py:552: in _terminate_live_server
    self._process.terminate()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <Process(Process-1, initial)>

    def terminate(self):
        '''
            Terminate process; sends SIGTERM signal or uses TerminateProcess()
            '''
>       self._popen.terminate()
E       AttributeError: 'NoneType' object has no attribute 'terminate'

..\appdata\local\programs\python\python36\lib\multiprocessing\process.py:116: AttributeError
-------------------------- Captured stderr teardown ---------------------------
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\users\lanzi\appdata\local\programs\python\python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "c:\users\lanzi\appdata\local\programs\python\python36\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
========================== 1 failed in 1.92 seconds ===========================

**Comment by ignacio96** [comment]
En el repo mio por alguna razon no me aparecen los ultimos tres commits del branch dev de upstream, uno de esos es el commit "Mejora el ejemplo de test e2e". Puede ser por eso el error?

**Comment by RodrigoJacznik** [comment]
Eso mismo te iba a decir, si estas en windows actualiza el repo y te tiene que funcionar

**Comment by SantiClausen** [comment]
una consulta, ¿a que se refiere 'al path del sistema'? ¿hay que poner el archivo zip dentro de c/windows?

**Comment by RodrigoJacznik** [comment]
No, te dejo información sobre el path y como modificarlo

https://es.m.wikipedia.org/wiki/PATH_(informática)
https://medium.com/@01luisrene/como-agregar-variables-de-entorno-s-o-windows-10-e7f38851f11f

**Comment by SantiClausen** [comment]
segun parece, mi PATH lleva a varias carpetas. Copie el programa a una de esas carpetas, pero me da un error similar que al de arriba

**Comment by RodrigoJacznik** [comment]
Que error te da? Mándame captura de la carpeta y del path

**Comment by SantiClausen** [comment]
el error es este:
`============================= test session starts =============================
platform win32 -- Python 3.6.5, pytest-3.5.1, py-1.5.3, pluggy-0.6.0
rootdir: C:\Users\samsung\orderingg\test, inifile:
collected 1 item

test_e2e.py F                                                            [100%]

================================== FAILURES ===================================
_____________________________ Ordering.test_title _____________________________

self = <test.test_e2e.Ordering testMethod=test_title>
result = <TestCaseFunction 'test_title'>

    def __call__(self, result=None):
        """
            Does the required setup, doing it here means you don't have to
            call super.setUp in subclasses.
            """

        # Get the app
        self.app = self.create_app()

        self._configured_port = self.app.config.get('LIVESERVER_PORT', 5000)
        self._port_value = multiprocessing.Value('i', self._configured_port)

        # We need to create a context in order for extensions to catch up
        self._ctx = self.app.test_request_context()
        self._ctx.push()

        try:
>           self._spawn_live_server()

c:\program files (x86)\python36-32\lib\site-packages\flask_testing\utils.py:446:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <test.test_e2e.Ordering testMethod=test_title>

    def _spawn_live_server(self):
        self._process = None
        port_value = self._port_value

        def worker(app, port):
            # Based on solution: http://stackoverflow.com/a/27598916
            # Monkey-patch the server_bind so we can determine the port bound by Flask.
            # This handles the case where the port specified is `0`, which means that
            # the OS chooses the port. This is the only known way (currently) of getting
            # the port out of Flask once we call `run`.
            original_socket_bind = socketserver.TCPServer.server_bind
            def socket_bind_wrapper(self):
                ret = original_socket_bind(self)

                # Get the port and save it into the port_value, so the parent process
                # can read it.
                (_, port) = self.socket.getsockname()
                port_value.value = port
                socketserver.TCPServer.server_bind = original_socket_bind
                return ret

            socketserver.TCPServer.server_bind = socket_bind_wrapper
            app.run(port=port, use_reloader=False)

        self._process = multiprocessing.Process(
            target=worker, args=(self.app, self._configured_port)
        )

>       self._process.start()

c:\program files (x86)\python36-32\lib\site-packages\flask_testing\utils.py:486:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <Process(Process-1, initial)>

    def start(self):
        '''
            Start child process
            '''
        assert self._popen is None, 'cannot start a process twice'
        assert self._parent_pid == os.getpid(), \
               'can only start a process object created by current process'
        assert not _current_process._config.get('daemon'), \
               'daemonic processes are not allowed to have children'
        _cleanup()
>       self._popen = self._Popen(self)

c:\program files (x86)\python36-32\lib\multiprocessing\process.py:105:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

process_obj = <Process(Process-1, initial)>

    @staticmethod
    def _Popen(process_obj):
>       return _default_context.get_context().Process._Popen(process_obj)

c:\program files (x86)\python36-32\lib\multiprocessing\context.py:223:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

process_obj = <Process(Process-1, initial)>

    @staticmethod
    def _Popen(process_obj):
        from .popen_spawn_win32 import Popen
>       return Popen(process_obj)

c:\program files (x86)\python36-32\lib\multiprocessing\context.py:322:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <multiprocessing.popen_spawn_win32.Popen object at 0x042CE9B0>
process_obj = <Process(Process-1, initial)>

    def __init__(self, process_obj):
        prep_data = spawn.get_preparation_data(process_obj._name)

        # read end of pipe will be "stolen" by the child process
        # -- see spawn_main() in spawn.py.
        rhandle, whandle = _winapi.CreatePipe(None, 0)
        wfd = msvcrt.open_osfhandle(whandle, 0)
        cmd = spawn.get_command_line(parent_pid=os.getpid(),
                                     pipe_handle=rhandle)
        cmd = ' '.join('"%s"' % x for x in cmd)

        with open(wfd, 'wb', closefd=True) as to_child:
            # start process
            try:
                hp, ht, pid, tid = _winapi.CreateProcess(
                    spawn.get_executable(), cmd,
                    None, None, False, 0, None, None, None)
                _winapi.CloseHandle(ht)
            except:
                _winapi.CloseHandle(rhandle)
                raise

            # set attributes of self
            self.pid = pid
            self.returncode = None
            self._handle = hp
            self.sentinel = int(hp)
            util.Finalize(self, _winapi.CloseHandle, (self.sentinel,))

            # send information to child
            set_spawning_popen(self)
            try:
                reduction.dump(prep_data, to_child)
>               reduction.dump(process_obj, to_child)

c:\program files (x86)\python36-32\lib\multiprocessing\popen_spawn_win32.py:65:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

obj = <Process(Process-1, initial)>, file = <_io.BufferedWriter name=8>
protocol = None

    def dump(obj, file, protocol=None):
        '''Replacement for pickle.dump() using ForkingPickler.'''
>       ForkingPickler(file, protocol).dump(obj)
E       AttributeError: Can't pickle local object 'LiveServerTestCase._spawn_live_server.<locals>.worker'

c:\program files (x86)\python36-32\lib\multiprocessing\reduction.py:60: AttributeError

During handling of the above exception, another exception occurred:

self = <test.test_e2e.Ordering testMethod=test_title>
result = <TestCaseFunction 'test_title'>

    def __call__(self, result=None):
        """
            Does the required setup, doing it here means you don't have to
            call super.setUp in subclasses.
            """

        # Get the app
        self.app = self.create_app()

        self._configured_port = self.app.config.get('LIVESERVER_PORT', 5000)
        self._port_value = multiprocessing.Value('i', self._configured_port)

        # We need to create a context in order for extensions to catch up
        self._ctx = self.app.test_request_context()
        self._ctx.push()

        try:
            self._spawn_live_server()
            super(LiveServerTestCase, self).__call__(result)
        finally:
            self._post_teardown()
>           self._terminate_live_server()

c:\program files (x86)\python36-32\lib\site-packages\flask_testing\utils.py:450:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
c:\program files (x86)\python36-32\lib\site-packages\flask_testing\utils.py:552: in _terminate_live_server
    self._process.terminate()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <Process(Process-1, initial)>

    def terminate(self):
        '''
            Terminate process; sends SIGTERM signal or uses TerminateProcess()
            '''
>       self._popen.terminate()
E       AttributeError: 'NoneType' object has no attribute 'terminate'

c:\program files (x86)\python36-32\lib\multiprocessing\process.py:116: AttributeError
-------------------------- Captured stderr teardown ---------------------------
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\program files (x86)\python36-32\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "c:\program files (x86)\python36-32\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
========================== 1 failed in 1.24 seconds ===========================
`
la ultima carpeta que aparece en el path es la siguiente:
![image](https://user-images.githubusercontent.com/38263254/40579867-7519cf76-6108-11e8-900f-c394c3d8cb9c.png)
![image](https://user-images.githubusercontent.com/38263254/40579868-804bc75a-6108-11e8-9735-8f4947e80c0b.png)
ahi la ubique

**Comment by RodrigoJacznik** [comment]
Actualiza el repo y te tiene que funcionar

**Comment by SantiClausen** [comment]
¿el repositorio local? ¿O debo actualizar el repositorio remoto de mi branch?

**Comment by RodrigoJacznik** [comment]
Deberías actualizar tu repo y después el branch. Pushear todo para que tus compañeros tengan los cambios.

**Comment by SantiClausen** [comment]
solo para asegurarme, ¿pusheo todo desde el branch donde estoy trabajando al dev del repo remoto, y después pusheo el branch en si?

**Comment by RodrigoJacznik** [comment]
Desde dev hace un pull de nuestro repo, después hace un push a tu repo.
Si queres actualizar un branch haces un merge.

**Comment by ignacio96** [comment]
Actualice el repo y se resolvio el problema. Ahora se ejecuta el test, corre la aplicacion y se queda esperando (wating for localhost) hasta que me devuelve en la consola de windows un error (timeout exception)

**Comment by SantiClausen** [comment]
a mi tambien me resolvio el error el problema y pudo correr, pero me dio un error distinto. 
```
test_e2e.py F                                                            [100%]

================================== FAILURES ===================================
_____________________________ Ordering.test_title _____________________________

self = <test.test_e2e.Ordering testMethod=test_title>

    def test_title(self):
        driver = self.driver
        driver.get(self.baseURL)
        add_product_button = driver.find_element_by_xpath('/html/body/main/div[1                                                                                                                ]/div/button')
        add_product_button.click()
        modal = driver.find_element_by_id('modal')
>       assert modal.is_displayed(), "El modal no esta visible"
E       AssertionError: El modal no esta visible
E       assert False
E        +  where False = <bound method WebElement.is_displayed of <selenium.web                                                                                                                driver.remote.webelement.WebElement (session="4d675984548378f3f39dd0ee990563d8",                                                                                                                 element="0.7537281334902985-2")>>()
E        +    where <bound method WebElement.is_displayed of <selenium.webdriver                                                                                                                .remote.webelement.WebElement (session="4d675984548378f3f39dd0ee990563d8", eleme                                                                                                                nt="0.7537281334902985-2")>> = <selenium.webdriver.remote.webelement.WebElement                                                                                                                 (session="4d675984548378f3f39dd0ee990563d8", element="0.7537281334902985-2")>.is                                                                                                                _displayed

test_e2e.py:47: AssertionError
========================== 1 failed in 71.22 seconds ==========================

```

**Comment by SantiClausen** [comment]
momento, no, arregle unas cosas en el branch y ahora funciona. Pero despues de hacer el test, no me quiere devolver el control del git bash

**Comment by RodrigoJacznik** [comment]
Ignacio, subí acá como te quedó test_e2e.ph

Santi, en realidad te falló el test. Se abre el chrome?

**Comment by SantiClausen** [comment]
si se abrió, ahora el problema en si esta solucionado. El tema es que ahora no tengo control del git bash

**Comment by RodrigoJacznik** [comment]
Cuando actualizaste el repo también te bajo un cambio en routes.py?

**Comment by SantiClausen** [comment]
si, solo debía hacer un commit para que lo agarre. Habia un par de archivos que tenia problemas de merging, pero los arregle y quedaron bien

**Comment by RodrigoJacznik** [comment]
Subime el archivo de test

**Comment by SantiClausen** [comment]
```
import unittest
import os
import time
import threading

from selenium import webdriver

from app import create_app, db
from app.models import Product, Order, OrderProduct

basedir = os.path.abspath(os.path.dirname(__file__))

from werkzeug.serving import make_server

class Ordering(unittest.TestCase):
    # Creamos la base de datos de test
    def setUp(self):
        self.app = create_app()
        self.app.config.update(
            SQLALCHEMY_DATABASE_URI='sqlite:///' + os.path.join(basedir, 'test.d                                   b'),
            SQLALCHEMY_TRACK_MODIFICATIONS=False,
            TESTING=True
        )

        self.app_context = self.app.app_context()
        self.app_context.push()

        self.baseURL = 'http://localhost:5000'

        db.session.commit()
        db.drop_all()
        db.create_all()

        self.t = threading.Thread(target=self.app.run)
        self.t.start()

        time.sleep(1)

        self.driver = webdriver.Chrome()

    def test_title(self):
        driver = self.driver
        driver.get(self.baseURL)
        add_product_button = driver.find_element_by_xpath('/html/body/main/div[1                                   ]/div/button')
        add_product_button.click()
        modal = driver.find_element_by_id('modal')
        assert modal.is_displayed(), "El modal no esta visible"

    def tearDown(self):
        self.driver.get('http://localhost:5000/shutdown')

        db.session.remove()
        db.drop_all()
        self.driver.close()
        self.app_context.pop()

if __name__ == "__main__":
    unittest.main()
```
no entiendo bien cual es el problema. El test parece funcionar bien, es solo que git bash se cuelga cuando el test termina

**Comment by ignacio96** [comment]
@RodrigoJacznik  Te paso el codigo o lo que me devuelve en la consola?

**Comment by RodrigoJacznik** [comment]
Yo también lo veo normal. Pasame el routes.py

**Comment by SantiClausen** [comment]
codigo de routes.py
```
from sqlalchemy import and_

from app import db
from app.models import Product, Order, OrderProduct
from flask import request, jsonify, render_template, abort, current_app

from flask import Blueprint
rest = Blueprint('rest', __name__, template_folder='templates')

@rest.route("/")
def hello():
    return render_template('orders.html')

@rest.route("/product", methods=['GET', 'POST'])
def products():
    """
    Endpoint para obtener todos los productos o crear uno nuevo
    :return:
    """
    if request.method == 'POST':
        # Crea un nuevo producto recibiendo un JSON con atributos name y price
        # Ejemplo: {'name': 'Tenedor', 'price': 50}
        p = Product(name=request.get_json()['name'], price=request.get_json()['price'])
        db.session.add(p)
        db.session.commit()
        return jsonify(p.serialize)
    else:
        # Obtiene todos los productos disponibles
        p = Product.query.all()
        return jsonify([i.serialize for i in p])

@rest.route("/order", methods=['GET'])
def orders():
    """
    Obtiene todas las ordenes
    """

    orders = Order.query.all()
    return jsonify([order.serialize for order in orders])

@rest.route("/order/<pk>", methods=['GET'])
def order(pk):
    """
    Obtiene la orden con id `pk`

    Si no se encuentra la orden, se responde con un 404
    """

    # obtenemos las ordenes
    order = Order.query.get(pk)

    # Si la orden no existe, levantamos el error
    if (not order):
        return jsonify({ 'error': 'not-found' }), 404

    return jsonify(order.serialize)

@rest.route("/order/<pk>/product", methods=['POST'])
def addProductToOrder(pk):
    # obtenemos las ordenes
    order = Order.query.get(pk)

    # Si la orden no existe, levantamos el error
    if (not order):
        return jsonify({ 'error': '<order {}> not found'.format(pk) }), 404

    product_data = request.get_json()
    product = product_data['product']

    product_exists = any([
        p.product.id == product['id'] for p in order.products
    ])

    # Si el producto existe en la orden levantamos el error
    if (product_exists):
        return jsonify({
            'error': '<product {}> exists in <order {}>. Use PUT method'
                .format(product['id'], pk)
        }), 400

    orderProduct = OrderProduct(quantity=product_data['quantity'])
    orderProduct.product = Product.query.get(product['id'])
    order.products.append(orderProduct)

    db.session.add(order)
    db.session.commit()

    return jsonify(order.serialize), 201

@rest.route("/order/<pk_order>/product/<pk_product>", methods=['GET', 'PUT', 'DELETE'])
def order_product_detail(pk_order, pk_product):
    """
    Obtiene un producto de una orden y modifica un producto de una orden

    Si no se encuentra la orden, se responde con un 404.
    Si no se encuentra el producto, se responde con un 404
    """

    order_product = OrderProduct.query.filter(and_(OrderProduct.order_id==pk_order, OrderProduct.product_id==pk_product)).all()[0]

    if (not order_product):
        return jsonify({ 'error': 'not-found' }), 404

    order_product_json = order_product.serialize

    if request.method == 'PUT':
        new_quantity = request.get_json().get('quantity', False)

        if (new_quantity):
            order_product.quantity = int(new_quantity)
            order_product_json = order_product.serialize

    if request.method == 'GET':
        return jsonify(order_product_json)

    if request.method == 'DELETE':
        db.session.delete(order_product)

    db.session.commit()
    return jsonify(order_product_json)

@rest.route('/shutdown')
def server_shutdown():
    if not current_app.testing:
        abort(404)
    shutdown = request.environ.get('werkzeug.server.shutdown')
    if not shutdown:
        abort(500)

    shutdown()
    return 'Shutting down...'
```

**Comment by ignacio96** [comment]
te paso el test

import unittest
import os
import time
import threading

from selenium import webdriver

from app import create_app, db
from app.models import Product, Order, OrderProduct

basedir = os.path.abspath(os.path.dirname(__file__))

from werkzeug.serving import make_server

class Ordering(unittest.TestCase):
    # Creamos la base de datos de test
    def setUp(self):
        self.app = create_app()
        self.app.config.update(
            SQLALCHEMY_DATABASE_URI='sqlite:///' + os.path.join(basedir, 'test.db'),
            SQLALCHEMY_TRACK_MODIFICATIONS=False,
            TESTING=True
        )

        self.app_context = self.app.app_context()
        self.app_context.push()

        self.baseURL = 'http://localhost:5000'

        db.session.commit()
        db.drop_all()
        db.create_all()

        self.t = threading.Thread(target=self.app.run)
        self.t.start()

        time.sleep(1)

        self.driver = webdriver.Chrome()

    def test_title(self):
        driver = self.driver
        driver.get(self.baseURL)
        add_product_button = driver.find_element_by_xpath('/html/body/main/div[1]/div/button')
        add_product_button.click()
        modal = driver.find_element_by_id('modal')
        assert modal.is_displayed(), "El modal no esta visible"

    def tearDown(self):
        self.driver.get('http://localhost:5000/shutdown')

        db.session.remove()
        db.drop_all()
        self.driver.close()
        self.app_context.pop()

if __name__ == "__main__":
    unittest.main()

**Comment by RodrigoJacznik** [comment]
Por ahora corta la ejecución con ctrl+c. Cuando tenga una computadora cerca lo reviso mejor
