### ISSUE TITLE
Problemas para instalar los requerimientos

### ISSUE THREAD

**Issue by CarlosdAndrade** [frlp-utn-is-2018/orderingg#37]
Hola Profesor, cuando intento instalar los requerimientos me sale las siguiente info:

C:\Python34\Scripts>pip install -r D:\Mis documentos\Ingenie\Nuevo2\orderingg\re
quirements.txt
Exception:
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\pip\basecommand.py", line 122, in main
    status = self.run(options, args)
  File "C:\Python34\lib\site-packages\pip\commands\install.py", line 257, in run

    InstallRequirement.from_line(name, None))
  File "C:\Python34\lib\site-packages\pip\req.py", line 172, in from_line
    return cls(req, comes_from, url=url, prereleases=prereleases)
  File "C:\Python34\lib\site-packages\pip\req.py", line 70, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "C:\Python34\lib\site-packages\pip\_vendor\pkg_resources.py", line 2606,
in parse
    reqs = list(parse_requirements(s))
  File "C:\Python34\lib\site-packages\pip\_vendor\pkg_resources.py", line 2544,
in parse_requirements
    line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
  File "C:\Python34\lib\site-packages\pip\_vendor\pkg_resources.py", line 2512,
in scan_list
    raise ValueError("Expected "+item_name+" in",line,"at",line[p:])
ValueError: ('Expected version spec in', 'documentos\\Ingenie\\Nuevo2\\orderingg
\\requirements.txt', 'at', '\\Ingenie\\Nuevo2\\orderingg\\requirements.txt')

Storing debug log for failure in C:\Users\Alumno\pip\pip.log

C:\Python34\Scripts>

Necesitaría ayuda para resolverlo asi lo trabajo. Saludos

**Comment by RodrigoJacznik** [comment]
Hola.
No es necesario ejecutar `pip` en la carpeta de python, ejecutalo como se indica en el readme en la carpeta del proyecto.

Si seguís teniendo problemas, mandame por acá el contenido del archivo re
quirements.txt.

**Comment by CarlosdAndrade** [comment]
Joya Profesor, ahi funcionó. Gracias
