### ISSUE TITLE
Problema al correr los test que se encuentran en la carpeta test

### ISSUE THREAD

**Issue by CarlosdAndrade** [frlp-utn-is-2018/orderingg#38]
Hola profesor, al correr los test me salen los siguientes errores

D:\Mis documentos\Ingenie\Nuevo2\test>c:\python34\python test_unit.py
Traceback (most recent call last):
  File "test_unit.py", line 7, in <module>
    from app import create_app, db
ImportError: No module named 'app'

D:\Mis documentos\Ingenie\Nuevo2\test>c:\python34\python test_e2e.py
Traceback (most recent call last):
  File "test_e2e.py", line 7, in <module>
    from app import create_app, db
ImportError: No module named 'app'

D:\Mis documentos\Ingenie\Nuevo2\test>

El Selenium lo instalo bien para Python y para Chrome

**Comment by RodrigoJacznik** [comment]
Hola,

Usa pytest para correr los test.
Ejecuta el comando `pytest` en la el directorio del proyecto.

**Comment by CarlosdAndrade** [comment]
Hola profesor, queria consultarle si esta bien el codigo de eliminar producto que ayer en realidad el test no hacia nada, me di cuenta, insertaba los productos y nunca los comitee. Lo que hago en el test es despues de insertar el producto y eliminar fijarme si todavia esta en la base de datos. Quería saber si esta bien implementado de esta manera:


```
def test_borrar(self):
    o = Order(id=1)
    db.session.add(o)
    db.session.commit()

    p = Product(id=1, name='Cuchillo', price=20)
    db.session.add(p)
    db.session.commit()

    orderProduct = OrderProduct(order_id=1, product_id=1, quantity=1, product=p)
    db.session.add(orderProduct)
    db.session.commit()

    resp = self.client.delete('order/1/product/1')

    self.assert200(resp, "Fallo el Test")
    res=orderProduct.query.all()
    assert res=1,'Fallo el test, no se elimino'
```
Gracias por su tiempo profesor. Saludos
________________________________
De: Rodrigo Jacznik <notifications@github.com>
Enviado: miércoles, 23 de mayo de 2018 03:22
Para: frlp-utn-is-2018/orderingg
Cc: CARLOS ANDRADE; Author
Asunto: Re: [frlp-utn-is-2018/orderingg] Problema al correr los test que se encuentran en la carpeta test (#38)


Hola,

Usa pytest para correr los test.
Ejecuta el comando pytest en la el directorio del proyecto.

**Comment by RodrigoJacznik** [comment]
Hola, el test sigue estando mal, el modelo es el siguiente:

![diagrama](https://user-images.githubusercontent.com/2715743/40692997-72af7f30-638b-11e8-8d8a-3871d2863825.png)

`res = orderProduct.query.all()`

es equivalente a la siguiente secuencia de SQL con la correspondiente transformación a objetos de python

`SELECT * FORM orderProduct;`

y en

`assert res=1,'Fallo el test, no se elimino'`

estas comprobando que res sea igual a 1, cosa que nunca va a suceder.

**Comment by CarlosdAndrade** [comment]
Hola profesor, ahi mejore el test_ borrar, espero que este mejor:

def test_borrar(self):
    t = {
        'id': 1,
        'name': 'Cuchillo',
        'price': 20
    }

    self.client.post('/product', data=json.dumps(t), content_type='application/json')

    o = Order(id=1)
    db.session.add(o)

    orderProduct = OrderProduct(order_id=1, product_id=1, quantity=1, product=t)
    db.session.add(orderProduct)
    db.session.commit()
    d = {"quantity": 5, "order_id": 1, "product": t, "product": {"id": 1}}
    self.client.post('/order/1/product', data=json.dumps(d), content_type='application/json')

    self.client.delete('order/1/product/1')
    res= orderProduct.query.get(1)
    If len(res) != 0 :
           Print ("No se elimino el producto")

Disculpe profesor que se lo mando por aca. Gracias


________________________________
De: Rodrigo Jacznik <notifications@github.com>
Enviado: miércoles, 30 de mayo de 2018 00:57
Para: frlp-utn-is-2018/orderingg
Cc: CARLOS ANDRADE; Author
Asunto: Re: [frlp-utn-is-2018/orderingg] Problema al correr los test que se encuentran en la carpeta test (#38)


Hola, el test sigue estando mal, el modelo es el siguiente:

[diagrama]<https://user-images.githubusercontent.com/2715743/40692968-437c90a4-638b-11e8-8fe4-18c439576962.png>

[https://user-images.githubusercontent.com/2715743/40692968-437c90a4-638b-11e8-8fe4-18c439576962.png]

res = orderProduct.query.all()

es equivalente a la siguiente secuencia de SQL con la correspondiente transformación a objetos de python

SELECT * FORM orderProduct;

y en

assert res=1,'Fallo el test, no se elimino'

estas comprobando que res sea igual a 1, cosa que nunca va a suceder.

**Comment by RodrigoJacznik** [comment]
Carlos, estas pudiendo probar los test?
Si el código que pegaste es exactamente el que tenes en tu proyecto, no debería andar. Print (con P no es una función de python)

El test no tiene ningún assert, no estas testeando nada.

**Comment by CarlosdAndrade** [comment]
Hola profesor, aca le envío la ultima corrección de los dos test de unidad el de borrar un producto y el de agregar un producto con nombre vacío, haber si voy bien para continuar con los adicionales:


    def test_borrar(self):
        p = Product(name='cuchillo', price=20)
        db.session.add(p)
        db.session.commit()

        o = Order(id=1)
        db.session.add(o)
        db.session.commit()

        orderP = OrderProduct(order_id=1, product_id=1, quantity=-5, product=p)
        o.products.append(orderP)
        db.session.add(o)
        db.session.commit()
        op = {"quantity": 5, "order_id": 1, "product": p, "product": {"id": 1}}
        self.client.post('/order/1/product', data=json.dumps(op), content_type='application/json')

        self.client.delete('order/1/product/1')
        res = OrderProduct.query.all()
        if len(res) != 0 :
               print ("No se elimino el producto")

# Actividad 3 inciso 3c
    def test_name_vacio(self):
        p = Product(id=1, name='', price=20)
        db.session.add(p)

        o = Order(id=1)
        db.session.add(o)
        db.session.commit()

        res = Product.query.all()
        if len(res) != 0 :
               print ("Se agrego producto con nombre vacio, FALLO el test")

Gracias profesor


________________________________
De: Rodrigo Jacznik <notifications@github.com>
Enviado: miércoles, 23 de mayo de 2018 03:22
Para: frlp-utn-is-2018/orderingg
Cc: CARLOS ANDRADE; Author
Asunto: Re: [frlp-utn-is-2018/orderingg] Problema al correr los test que se encuentran en la carpeta test (#38)


Hola,

Usa pytest para correr los test.
Ejecuta el comando pytest en la el directorio del proyecto.

**Comment by CarlosdAndrade** [comment]
Ahi mire lo de los assert para saber cual aplicar bien. Ahi le mando las correcciones hechas:


# Actividad 3 inciso 3a

    def test_borrar(self):
        p = Product(name='cuchillo', price=20)
        db.session.add(p)
        db.session.commit()

        o = Order(id=1)
        db.session.add(o)
        db.session.commit()

        op = OrderProduct(order_id=1, product_id=1, quantity=-5, product=p)
        o.products.append(op)
        db.session.add(o)
        db.session.commit()
        self.client.delete('order/1/product/1')
        self.assertNotIn(op, db.session, "No se eliminó el producto de la orden")

# Actividad 3 inciso 3c
    def test_name_vacio(self):
        p = Product(id=1, name='', price=20)
        db.session.add(p)

        o = Order(id=1)
        db.session.add(o)
        db.session.commit()

        p = Product.query.all() [0]
        self.assertTrue(p.name == "", "Fallo el test. El nombre no debe estar vacío")

Haber si ahí esta mejor profesor.

________________________________
De: Rodrigo Jacznik <notifications@github.com>
Enviado: miércoles, 30 de mayo de 2018 12:24
Para: frlp-utn-is-2018/orderingg
Cc: CARLOS ANDRADE; Author
Asunto: Re: [frlp-utn-is-2018/orderingg] Problema al correr los test que se encuentran en la carpeta test (#38)


Carlos, estas pudiendo probar los test?
Si el código que pegaste es exactamente el que tenes en tu proyecto, no debería andar. Print (con P no es una función de python)

El test no tiene ningún assert, no estas testeando nada.

**Comment by RodrigoJacznik** [comment]
Intenta basarte en el código de los otro repos entendiendo que es lo que esta pasando. No esta mal que leas código de otros chicos, pero pegarlo en tu código sin entender que es lo que hace si

Actividad 3 inciso 3a
`self.assertNotIn(op, db.session, "No se eliminó el producto de la orden")`

No es un assert correcto, esta buscando op en la session de la base de datos.

Actividad 3 inciso 3c

El assert no es correcto por 2 cosas

1. Si el modelo es correcto (no permite productos con nombres vacíos) el test va a levantar una excepción
2. En el assert estas comprobando que el producto tenga el nombre vacío y eso es justamente lo contrario al test 

Revisa bien el mail de la actividad que se te asigno porque me parece que no es esto.

**Comment by CarlosdAndrade** [comment]
Hola profesor, como esta. Le pido disculpas si lo ofendi o lo moleste por algo. Entiendo que estuve mal y me maneje de mal manera. Mil disculpas. Cerca del mediodia le envio lo que corregi con lo que creo que entendi bien igual le mando una explicacion de lo que para mi hace el codigo haber si es correcto lo que estoy entendiendo. Y por lo otro desde ya mil disculpas.

El may. 30, 2018 12:07, Rodrigo Jacznik <notifications@github.com> escribió:

Intenta basarte en el código de los otro repos entendiendo que es lo que esta pasando. No esta mal que leas código de otros chicos, pero pegarlo en tu código sin entender que es lo que hace si

Actividad 3 inciso 3a
self.assertNotIn(op, db.session, "No se eliminó el producto de la orden")

No es un assert correcto, esta buscando op en la session de la base de datos.

Actividad 3 inciso 3c

El assert no es correcto por 2 cosas

  1.  Si el modelo es correcto (no permite productos con nombres vacíos) el test va a levantar una excepción
  2.  En el assert estas comprobando que el producto tenga el nombre vacío y eso es justamente lo contrario al test

Revisa bien el mail de la actividad que se te asigno porque me parece que no es esto.

**Comment by RodrigoJacznik** [comment]
No hay que pedir disculpa por nada, lo que quería evitar es que mandes 100 mensajes intentando todo el código que encontraras hasta pegarle.
