### ISSUE TITLE
Error en iniciar BD con la versión nueva para los Test

### ISSUE THREAD

**Issue by Alexissiminkowich** [frlp-utn-is-2018/orderingg#41]
Buenos noches

Antes no salia.... ahora sale lo siguiente a ejecutar:

python fixture.py

Me esta saliendo lo siguiente:

Equipo@Equipo-PC MINGW32 ~/Desktop/ING DE SOFTWARE/orderingg (dev)
$ python fixture.py
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\sqlalchemy\util\_collections.py", line 999, in __call__
    return self.registry[key]
KeyError: 3580

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fixture.py", line 61, in <module>
    addProducts()
  File "fixture.py", line 48, in addProducts
    products = Product.query.all()
  File "C:\Python34\lib\site-packages\flask_sqlalchemy\__init__.py", line 514, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "C:\Python34\lib\site-packages\sqlalchemy\orm\scoping.py", line 74, in __call__
    return self.registry()
  File "C:\Python34\lib\site-packages\sqlalchemy\util\_collections.py", line 1001, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "C:\Python34\lib\site-packages\sqlalchemy\orm\session.py", line 2950, in __call__
    return self.class_(**local_kw)
  File "C:\Python34\lib\site-packages\flask_sqlalchemy\__init__.py", line 141, in __init__
    self.app = app = db.get_app()
  File "C:\Python34\lib\site-packages\flask_sqlalchemy\__init__.py", line 912, in get_app
    'No application found. Either work inside a view function or push'
RuntimeError: No application found. Either work inside a view function or push an application context. See http://flask-sqlalchemy.pocoo.org/contexts/.

Que esta mal?

**Comment by RodrigoJacznik** [comment]
Hola,

puede ser que hayas mergeado antes de que suba un fix en el fixture.py
Fíjate si tenes diferencias entre los archivos que están en este repo y en el tuyo.

**Comment by Alexissiminkowich** [comment]
Arreglado!! Era eso, sincronice de nuevo y modifique el gitignore para ignorar los caches. Saludos!
