### ISSUE TITLE
Problemas con el Test de integracion opcional de verificar que se muestre la notificacion

### ISSUE THREAD

**Issue by leo-frison** [frlp-utn-is-2018/orderingg#73]
Hola estuve tratanto de corre este codigo , lo analice linea por linea y me tira un error sintactico ..la verdad nose que pueda llegar a ser el problema . me marca error en la ultima linea cuando quiero verificar el resultado esperado o por lo menos ahi es donde me lo marca , creo que el assertEqual es la mejor opcion , probe con el assertTrue tmb pero no veo condicion que deba evaluarse .. ahi lo paso explicandolo linea por linea :    

```python
def test_Notificacion_Aparece(self):
        #Genero producto
        p = Product(id=1, name = 'Mesa', price = 500)
        db.session.add(p)
        #Genero una order
        o = Order(id=1)
        db.session.add(o)
        #Asigno la orden al producto creado
        op = OrderProduct(product = prod, quantity = 1)
        db.session.add(op)
        db.session.commit()
        #Me traigo la base
        driver = self.driver
        driver.get(self.baseURL)
        #Tomo la ruta del boton agregar producto copiando su xpath
        agregar = driver.find_element_by_xpath("/html/body/main/div[1]/div/button").click()
        #Busco el elemento seleccionar producto 
        producto = driver.find_element_by_id("select-prod")
        #Selecciono el elemento visible Mesa en este caso ya q es el que quiero repetir guardar
        #la mesa para que me salte la notificacion
        producto.select_by_visible_text("Mesa")
        #Busco el elemento cantidad
        cantidad = driver.find_element_by_id("quantity")
        #Edito la cantidad 
        cantidad.SendKeys('1')
        #Busco el elemento boton guardar y clickeo
        guardar = driver.find_element_by_id("save-button").click()
        #busco el elemento notificacion y lo muestro
        noti = driver.find_element_by_id("noti").is_displayed()
        #verifico que aparesca la notificacion
        self.assertEqual(noti, "TRUE", "No aparece la notificación")  //EL ERROR ME LO MARCA ACA.
```

**Comment by RodrigoJacznik** [comment]
Cual es el error?

La ultima linea deberia ser:
`self.assertEqual(noti, True, "No aparece la notificación")`

**Comment by leo-frison** [comment]
NOP ...ya lo intente antes y lo repeti de nuevo ... me sigue saltando lo mismo una y otra ves .... y en la misma linea me marca siempre...

../.local/lib/python2.7/site-packages/_pytest/python.py:412: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
../.local/lib/python2.7/site-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
E     File "/home/leonardo/orderingg/test/test_e2e.py", line 184
E   SyntaxError: Non-ASCII character '\xc3' in file /home/leonardo/orderingg/test/test_e2e.py on line 184, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
=========================== 1 error in 0.21 seconds ============================

**Comment by RodrigoJacznik** [comment]
Estas usando python2 hace lo posible para pasarte a python3, era requisito desde el primer día.
Fíjate que en el error hay un link https://www.python.org/dev/peps/pep-0263/, dentro de ese link hay una posible solución.

**Comment by leo-frison** [comment]
../.local/lib/python3.6.5/site-packages/_pytest/python.py:412: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
../.local/lib/python3.6.5/site-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
E     File "/home/leonardo/orderingg/test/test_e2e.py", line 162
E   SyntaxError: Non-ASCII character '\xc3' in file /home/leonardo/orderingg/test/test_e2e.py on line 162, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!


...leonardo@leonardo-HP-1000-Notebook-PC:~/.local/lib/python3.6.5/site-packages/_pytest$ python --version
Python 3.6.5 .... ya le cambie la version usando un metodo de alias .. me sigue tirando el mismo error aunque no entiendo porque los demas test se me corren bien y las fallas sintacticas siempre me mostraban el mismo error y ruta .... con una modificacion sintactica siempre basto para solucionarlo ... de ultima tengo otra forma de resolver el mismo ejercicio que falla pero en la ejecucion ..

**Comment by RodrigoJacznik** [comment]
Fíjate el encoding del archivo. En ocasiones cuando copias y pegas de otro lado se lleva el texto en otro encoding.
Escribí es línea a mano.

No es un error de sintaxis, es un error de encoding

**Comment by leo-frison** [comment]
Al final el truco de ayer que hice con el alias no me cambio la version a python 3 ... nose que hizo eso del alias pero tengo ubuntu y me toma esta version de python como si fuera parte de la existencia del sistema operativo..hasta es complicado desinstalarla .... aun asi esa linea es la que me marca y no me quiero comer la cabeza en vano buscando solucionar algo que me pueda traer problemas .. si el codigo esta bien .. te paso todos mis codigos explicados linea por linea .. los demas se ejecutan lo mas bien .. me toco el modal de integracion que es el unico que pruebo con la tabla cargada..los demas salen sin falla , si te parece bien en breve te paso los unitest que hice del punto 1. el del input y el de orderprice explicados linea a linea e intento hacer otro .. pero porfa lo del python 3 perdonamelo .. me la instale pero no me toma la version .. siempre se queda con la 2.7 .. te juro que lo intente demasiado..
Esto es lo que lei en varios post queriendo pasarme a python 3 ..
Como ya debe haber notado que Ubuntu 16.04 tiene 'python 2.7.12' por defecto. Para verificar la versión por defecto de python, corra debajo de la línea

  $ python -V 
debería devolver 'Python 2.7.12'

Se recomienda que no intentemos modificar / desinstalar este paquete predeterminado de python porque podría haber muchos otros archivos / aplicaciones del sistema que dependen de él, y podría crear algunos errores o problemas inesperados si desinstalamos este paquete predeterminado de python.

**Comment by RodrigoJacznik** [comment]
Por eso, revisa el encoding del archivo, eso es lo que te dice el error.

Que alias estás usando?

**Comment by leo-frison** [comment]
leonardo@leonardo-HP-1000-Notebook-PC:~/orderingg$ python --version
Python 2.7.15rc1
leonardo@leonardo-HP-1000-Notebook-PC:~/orderingg$ python3 --version
Python 3.6.5
leonardo@leonardo-HP-1000-Notebook-PC:~/orderingg$ alias python=python3
leonardo@leonardo-HP-1000-Notebook-PC:~/orderingg$ python --version
Python 3.6.5
........................ Esto es lo que me dejo hacer ayer ... pero hoy cuando la prendi volvio al 2.7 ... no me lo toma el 3 ... voy a romper la notebook si le sigo dando vueltas a esto jajaja...

**Comment by RodrigoJacznik** [comment]
Te dejo 2 links con la solucion:

Crear alias:
https://stackoverflow.com/questions/35435517/creating-an-alias-for-python3

Poner encoding:
http://python.org/dev/peps/pep-0263/

**Comment by leo-frison** [comment]
intente de nuevo ver lo del encoding ... nose que tocar porque todo lo que intento cambiar me salta error por ejemplo recien modifique el encoding de pytest y corri los test integrales :  pytest -v test/test_e2e.py
Traceback (most recent call last):
  File "/home/leonardo/.local/bin/pytest", line 10, in <module>
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
NameError: name 're' is not defined
.... cambie el re por un os ... vi los ejemplos que marcan que la onda si es utf-8
tenga ----> import os, sys .... tambien que la ruta es esta --------> #!/usr/local/bin/python
pero no tengo ese archivo python en la carpeta bin ....... esto es todo lo que tengo en esa carpeta :
https://user-images.githubusercontent.com/38389932/40882330-020233b8-66b5-11e8-9dfb-f7186635cd57.png

**Comment by RodrigoJacznik** [comment]
Pero eso no lo tenes que tocar vos, estas modificando las librerías, lo único que tenias que hacer era ponerle el encoding a tu archivo

**Comment by leo-frison** [comment]
si te referis a ponerle esto # -*- coding: utf-8 -*- ya lo tienen los archivos ... nose a que archivo te referis especificamente pero personalmente a mi no me parece q el problema sea la version de python ... si fuera eso no se me tendria que haber ejecutado nada rodri ...es lo que me parece.. no soy experto  solo quiero terminar con esto ... tengo todos los test a punto caramelo para mandartelos todos explicados y me pasan todos ..si me das el ok los pusheo .. a mi me toco hacer el metodo input , el orderprice y el integrador del modal del selenium ... osea los del punto 1) a,b y c .... y de opcional es este de las notificaciones que tiene este inconveniente pero el codigo ya me dijiste que esta bien ... por eso prefiero hacer otro test opcional que seguir con este tema ... lo intente .. de ultima lo vemos el lunes esto de q no me toma la version ..

**Comment by RodrigoJacznik** [comment]
Nadie tuvo ese error en python3 por eso recomendé que te cambies de versión. Yo digo que el error es de encoding porque es lo que te sale en consola.

El test no esta bien, el ultimo assert no es correcto, no es "True".

**Comment by leo-frison** [comment]
ahi se me corrio todo el test  ya no me salta un error .. era un error en el espacio de la coma ... puede siempre me tiro el mismo error ... y siempre fue por la sintaxys .. pero a veces es una espacio de mas o algo muy muy sutil q te lo falla ... ahora que me lo paso si me falla el test ... osea que esa ultima linea estuvo mal todo este tiempo ? .. me habias dicho esto :
"Cual es el error?
La ultima linea deberia ser:
self.assertEqual(noti, True, "No aparece la notificación") " ......  si me decias antes que esa linea estaba mal se me habria ocurrido otras ideas como estas -------> self.assertEqual(len(noti),50, "No hay productos") o
        self.assertTrue(noti=="No se pueden agregar productos con nombre repetido","No hay productos")

**Comment by RodrigoJacznik** [comment]
Leo, te puse que estaba mal en la **primera respuesta** de este issue.
El error de encoding fue porque copiaste y pegaste código, si lo escribías a mano no te tiraba ese error porque el encoding iba a ser el correcto.

Todas las ideas que se te ocurrieron son incorrectas. La linea correcta es la que puse yo en la **primera respuesta**.

**Comment by leo-frison** [comment]
aaaaah ... ...sisi ..igual lo reehice a mano y corre bien.....ya esta solucionado lo del principio .. disculpa el malentendido ... ya subi los test ... gracias por la paciencia rodri (y) ..
